# Generated by Django 5.0.3 on 2024-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='Кредит'),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_remain',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаток по кредиту'),
        ),
        migrations.AlterField(
            model_name='user',
            name='debt',
            field=models.FloatField(blank=True, null=True, verbose_name='Долг долг клиента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='summ',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма всех покупок'),
        ),
    ]
