# Generated by Django 5.0.4 on 2024-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='QP',
            field=models.FloatField(default=1, verbose_name='Сумма стоимости товаров 1-го вида'),
        ),
    ]
