# Generated by Django 5.0.3 on 2024-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='summ',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=1, verbose_name='Стоимость товара'),
        ),
    ]
