# Generated by Django 5.0.3 on 2024-04-24 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_user_summ_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_money', models.IntegerField(default=1)),
                ('account_money', models.IntegerField(default=1)),
                ('credit_limit', models.IntegerField(default=1)),
                ('current_deubt', models.IntegerField(default=1)),
                ('credit_remains', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
