# Generated by Django 5.0.3 on 2024-04-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order2',
            old_name='current_deubt',
            new_name='current_debt',
        ),
    ]
