# Generated by Django 5.0.4 on 2024-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_current_deubt_order2_current_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order2',
            name='account_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order2',
            name='spent_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rest',
            field=models.FloatField(default=1, verbose_name='Осталось товаров'),
        ),
    ]
