# Generated by Django 5.0.3 on 2024-05-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_registration_code_user_registration_code_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registration_code_flag',
            new_name='flag_registration_code',
        ),
    ]
